### ISSUE TITLE
Remote debug with node process running in docker container

### ISSUE THREAD

**Issue by slavogiez** [willyelm/xatom-debug#4]
Hi,
I would like to debug a node process (express.js) running in a docker container. 

My container is exposing 3000 and 5858 ports.
The node process is running using --debug flag : node --debug app.js

If I run the command 'node debug localhost:5858' on my host, it connects correctly to the node process running in the container.

But I configured the atom-bugs plugin using "remote connection" to localhost and 5858 port and it doesn't seem to work : breakpoints are not working as expected.

If I toggle Atom developer tools, and then click on the play icon from atom-bugs, this error is displayed each second : 
launcher.ts:102 Uncaught (in promise) unable to find page with socket

Did I do anything wrong?

node version : 6.10
atom version : 1.15.0

**Comment by willyelm** [comment]
Please update to the latest version, also the tool requires a server of chrome v8 protocol, if you have node 6.3.X+ you can up a debugger server using:

`node --inspect-brk=5858 app.js`

since these are the default settings just select remote and it will work.

**Note**: I've made the first pause to be ignored forcing having at least one breakpoint to pause the script.
